#!/usr/bin/env bash
# mobsf/lib/compose.sh — MobSF compose bundle deploy and validation
# Version: 0.1.1
# Do not execute directly.

mobsf_compose_env_file() {
  local dir="${1:-$(mobsf_default_compose_dir)}"
  printf '%s/.env\n' "${dir}"
}

mobsf_generate_secret() {
  if have openssl; then
    openssl rand -hex 16
  else
    tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32
  fi
}

mobsf_pg_data_initialized() {
  local pg_dir
  pg_dir="$(mobsf_pg_dir)"
  [[ -d "${pg_dir}" ]] || return 1
  [[ -n "$(ls -A "${pg_dir}" 2>/dev/null || true)" ]]
}

# Create ~/MobSF/compose/.env for podman-compose variable substitution.
# Preserves existing .env; fresh installs get a random Postgres password.
mobsf_ensure_compose_env() {
  local compose_dir="${1:-$(mobsf_default_compose_dir)}"
  local env_file
  env_file="$(mobsf_compose_env_file "${compose_dir}")"

  if [[ -f "${env_file}" ]] && grep -q '^POSTGRES_PASSWORD=' "${env_file}" 2>/dev/null; then
    run_as_real_user chmod 0600 "${env_file}" 2>/dev/null || true
    ok "MobSF compose secrets: ${env_file}"
    return 0
  fi

  local password
  if mobsf_pg_data_initialized; then
    password="password"
    warn "Existing Postgres data — writing legacy POSTGRES_PASSWORD to .env (matches prior bundle default)"
  else
    password="$(mobsf_generate_secret)"
    info "Generating Postgres password for new MobSF install"
  fi

  run_as_real_user mkdir -p "${compose_dir}"
  run_as_real_user tee "${env_file}" > /dev/null <<EOF
# MobSF compose secrets — generated by mobsf toolkit (mode 0600, do not commit)
POSTGRES_PASSWORD=${password}
EOF
  run_as_real_user chmod 0600 "${env_file}"
  ok "MobSF compose secrets: ${env_file}"
}

mobsf_deploy_compose_bundle() {
  local dest="${1:-$(mobsf_default_compose_dir)}"
  local bundle="${MOBSF_BUNDLE_DIR}/compose"
  [[ -f "${bundle}/docker-compose.yml" ]] || die "MobSF bundle missing: ${bundle}/docker-compose.yml"
  [[ -f "${bundle}/nginx.conf" ]] || die "MobSF bundle missing: ${bundle}/nginx.conf"
  run_as_real_user mkdir -p "${dest}"
  cp -f "${bundle}/docker-compose.yml" "${bundle}/nginx.conf" "${dest}/"
  chown "$(real_user):$(real_user)" "${dest}/docker-compose.yml" "${dest}/nginx.conf" 2>/dev/null || true
  run_as_real_user chmod 0644 "${dest}/docker-compose.yml" "${dest}/nginx.conf" 2>/dev/null || true
  mobsf_ensure_compose_env "${dest}"
  ok "Deployed compose bundle to ${dest}"
  printf '%s\n' "${dest}"
}

mobsf_compose_check() {
  local file="${1:-$(mobsf_compose_file)}"
  [[ -f "${file}" ]] || return 1
  grep -qE '^\s*build\s*:' "${file}" && return 1
  grep -qE 'docker\.io/opensecurity/mobile-security-framework-mobsf:latest' "${file}" || return 1
  grep -qE 'postgresql_data:/var/lib/postgresql/data:.*U' "${file}" && return 1
  grep -qE 'postgresql_data:/var/lib/postgresql/data:[^[:space:]]*Z' "${file}" || return 1
  grep -qE 'mobsf_data:/home/mobsf/\.MobSF:[^[:space:]]*Z' "${file}" || return 1
  if ! grep -qE 'POSTGRES_PASSWORD=\$\{POSTGRES_PASSWORD\}' "${file}"; then
    return 1
  fi
  return 0
}

# Print specific guardrail failures (for doctor UI).
mobsf_compose_check_report() {
  local file="${1:-$(mobsf_compose_file)}"
  local issues=0
  [[ -f "${file}" ]] || { warn "  compose file missing"; return 1; }
  if grep -qE '^\s*build\s*:' "${file}"; then
    warn "  compose: contains 'build:' blocks (use mobsf_install.sh bundle)"
    issues=$((issues + 1))
  fi
  if ! grep -qE 'docker\.io/opensecurity/mobile-security-framework-mobsf:latest' "${file}"; then
    warn "  compose: MobSF image must be docker.io/opensecurity/mobile-security-framework-mobsf:latest"
    issues=$((issues + 1))
  fi
  if grep -qE 'postgresql_data:/var/lib/postgresql/data:.*U' "${file}"; then
    warn "  compose: postgres volume uses ':U' — use ':Z' only"
    issues=$((issues + 1))
  fi
  if ! grep -qE 'postgresql_data:/var/lib/postgresql/data:[^[:space:]]*Z' "${file}"; then
    warn "  compose: postgres volume must use ':Z' SELinux label"
    issues=$((issues + 1))
  fi
  if ! grep -qE 'mobsf_data:/home/mobsf/\.MobSF:[^[:space:]]*Z' "${file}"; then
    warn "  compose: mobsf_data volume must use ':Z' SELinux label"
    issues=$((issues + 1))
  fi
  if ! grep -qE 'POSTGRES_PASSWORD=\$\{POSTGRES_PASSWORD\}' "${file}"; then
    warn "  compose: POSTGRES_PASSWORD must use \${POSTGRES_PASSWORD} (not a hardcoded value)"
    issues=$((issues + 1))
  fi
  (( issues == 0 ))
}

mobsf_compose_validate() {
  local file="${1:-$(mobsf_compose_file)}"
  [[ -f "${file}" ]] || die "Compose file not found: ${file}"
  if grep -qE '^\s*build\s*:' "${file}"; then
    die "docker-compose.yml contains 'build:' blocks — use mobsf_install.sh to deploy Fedora bundle"
  fi
  if ! grep -qE 'docker\.io/opensecurity/mobile-security-framework-mobsf:latest' "${file}"; then
    die "docker-compose.yml must use docker.io/opensecurity/mobile-security-framework-mobsf:latest"
  fi
  if grep -qE 'postgresql_data:/var/lib/postgresql/data:.*U' "${file}"; then
    die "postgres volume has ':U' — use ':Z' only (run mobsf_install.sh)"
  fi
  if ! grep -qE 'postgresql_data:/var/lib/postgresql/data:[^[:space:]]*Z' "${file}"; then
    die "postgres volume must include ':Z' SELinux label — run mobsf_install.sh to redeploy bundle"
  fi
  if ! grep -qE 'mobsf_data:/home/mobsf/\.MobSF:[^[:space:]]*Z' "${file}"; then
    die "mobsf_data volume must include ':Z' SELinux label — run mobsf_install.sh to redeploy bundle"
  fi
}
